# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_str', models.TextField()),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NLRequestIPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(default='')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.NLRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_cmd', models.TextField()),
                ('score', models.FloatField()),
                ('num_upvotes', models.PositiveIntegerField(default=0)),
                ('num_downvotes', models.PositiveIntegerField(default=0)),
                ('num_stars', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.NLRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(default='')),
                ('upvoted', models.BooleanField(default=False)),
                ('downvoted', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Translation')),
            ],
        ),
    ]
