# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_str', models.TextField()),
                ('sub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_cmd', models.TextField()),
                ('score', models.FloatField()),
                ('num_votes', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tellina.NLRequest')),
            ],
        ),
    ]
