# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlrequest',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 2, 1, 43, 18, 411825)),
        ),
    ]
